# Generated by Django 4.0 on 2021-12-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated', '-full_name']},
        ),
        migrations.AddField(
            model_name='user',
            name='at_workplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_encodings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAS.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_id',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Иванов Иван Иванович', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pernr',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
