# Generated by Django 4.0 on 2021-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0003_alter_user_document_id_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='max_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
