# Generated by Django 4.0 on 2021-12-13 00:14

import TAS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0004_alter_department_max_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.svg', upload_to=TAS.models.path_and_rename),
        ),
    ]
