# Generated by Django 4.0 on 2021-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
