# Generated by Django 4.0 on 2021-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0006_user_is_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
