# Generated by Django 4.0 on 2021-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0007_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_time_1days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='work_time_30days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='work_time_7days',
            field=models.FloatField(default=0),
        ),
    ]
