# Generated by Django 4.0 on 2021-12-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0008_user_work_time_1days_user_work_time_30days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sick',
            field=models.BooleanField(default=False),
        ),
    ]
