# Generated by Django 4.0 on 2021-12-16 19:47

import TAS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0009_user_is_on_holiday_user_is_sick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='event_photo',
            field=models.ImageField(upload_to=TAS.models.path_and_rename),
        ),
    ]
