# Generated by Django 4.0 on 2021-12-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAS', '0010_alter_timetracking_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TAS.user'),
        ),
    ]
